### ISSUE TITLE
MIssing is.symbol

### ISSUE THREAD

**Issue by rtoal** [arasatasaygin/is.js#150]
Let's add some ES2015 features.

**Comment by planttheidea** [comment]
I don't think @arasatasaygin is maintaining this project anymore, nor has there been any activity on the account since May. I have forked the project and have rebranded it as isit.js ... you'd be surprised how many "is" variants exist on NPM. I have included isit.symbol(obj) as a method, using the second answer on the SO post you reference as the function basis.

Feel free to try it out if you'd like, just npm install initjs. I have also rearchitected it to be more ES2015 module based for ease of maintenance, so if you may find bugs, but I'll be on top of them.

**Comment by arasatasaygin** [comment]
Cool @planttheidea have fun with it. 
I'll be busy for a while and get back to this repo as of January 2016. I'll definitely check your changes and improvements.
Cheers

**Comment by jdalton** [comment]
Thanks @rtoal!

We'll keep an eye on [the popularity of the request](https://github.com/arasatasaygin/is.js/blob/master/CONTRIBUTING.md#feature-requests).

**Comment by komlev** [comment]
@jdalton, @rtoal Hi
Symbol is standard now and getting major support from browser.
Maybe it is time to resurrect this request?
