### ISSUE TITLE
Support for is.retina()

### ISSUE THREAD

**Issue by kfei** [arasatasaygin/is.js#153]
Is it make sense to add an API to indicate retina support?

There is a retina-related [discussion](http://stackoverflow.com/a/20413768/2504317) on StackOverflow.

**Comment by ApfelUser** [comment]
+1

**Comment by planttheidea** [comment]
I don't think @arasatasaygin is maintaining this project anymore, nor has there been any activity on the account since May. I have forked the project and have rebranded it as [isit.js](https://github.com/planttheidea/isit.js) ... you'd be surprised how many "is" variants exist on NPM. I have included isit.retina() as a method, using the second answer on the SO post you reference as the function basis.

Feel free to try it out if you'd like, just npm install initjs. I have also rearchitected it to be more ES2015 module based for ease of maintenance, so if you may find bugs, but I'll be on top of them.

**Comment by arasatasaygin** [comment]
Cool @planttheidea have fun with it. 
I'll be busy for a while and get back to this repo as of January 2016. I'll definitely check your changes and improvements.
Cheers

**Comment by jdalton** [comment]
Thanks @kfei!

We'll keep an eye on [the popularity of the request](https://github.com/arasatasaygin/is.js/blob/master/CONTRIBUTING.md#feature-requests).
